In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [28]:
dataset=pd.read_csv('forestfires.csv')
dataset

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  dayfri  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00       1   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00       0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00       0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00       1   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00       0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...     ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44       0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29       0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16       0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00       0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00       0   

     daymon  daysat  daysun  daythu  daytue  daywed  monthapr  monthaug  \
0         0       0       0       0       0       0         0         0   
1         0       0       0       0       1       0         0         0   
2         0       1       0       0       0       0         0         0   
3         0       0       0       0       0       0         0         0   
4         0       0       1       0       0       0         0         0   
..      ...     ...     ...     ...     ...     ...       ...       ...   
512       0       0       1       0       0       0         0         1   
513       0       0       1       0       0       0         0         1   
514       0       0       1       0       0       0         0         1   
515       0       1       0       0       0       0         0         1   
516       0       0       0       0       1       0         0         0   

     monthdec  monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  \
0           0         0         0         0         0         1         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         0         1         0   
4           0         0         0         0         0         1         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         0   

     monthnov  monthoct  monthsep size_category  
0           0         0         0         small  
1           0         1         0         small  
2           0         1         0         small  
3           0         0         0         small  
4           0         0         0         small  
..        ...       ...       ...           ...  
512         0         0         0         large  
513         0         0         0         large  
514         0         0         0         large  
515         0         0         0         small  
516         1         0         0         small  

[517 rows x 31 columns]

In [32]:
dataset.drop(columns=['month','day'],inplace=True)

In [33]:
pd.set_option('display.max_columns',None)
dataset.shape

(517, 29)

In [34]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 29 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   FFMC           517 non-null    float64
 1   DMC            517 non-null    float64
 2   DC             517 non-null    float64
 3   ISI            517 non-null    float64
 4   temp           517 non-null    float64
 5   RH             517 non-null    int64  
 6   wind           517 non-null    float64
 7   rain           517 non-null    float64
 8   area           517 non-null    float64
 9   dayfri         517 non-null    int64  
 10  daymon         517 non-null    int64  
 11  daysat         517 non-null    int64  
 12  daysun         517 non-null    int64  
 13  daythu         517 non-null    int64  
 14  daytue         517 non-null    int64  
 15  daywed         517 non-null    int64  
 16  monthapr       517 non-null    int64  
 17  monthaug       517 non-null    int64  
 18  monthdec  

In [35]:
dataset.isnull().sum()

FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [36]:
dataset.describe()

FFMC         DMC          DC         ISI        temp          RH  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean    90.644681  110.872340  547.940039    9.021663   18.889168   44.288201   
std      5.520111   64.046482  248.066192    4.559477    5.806625   16.317469   
min     18.700000    1.100000    7.900000    0.000000    2.200000   15.000000   
25%     90.200000   68.600000  437.700000    6.500000   15.500000   33.000000   
50%     91.600000  108.300000  664.200000    8.400000   19.300000   42.000000   
75%     92.900000  142.400000  713.900000   10.800000   22.800000   53.000000   
max     96.200000  291.300000  860.600000   56.100000   33.300000  100.000000   

             wind        rain         area      dayfri      daymon  \
count  517.000000  517.000000   517.000000  517.000000  517.000000   
mean     4.017602    0.021663    12.847292    0.164410    0.143133   
std      1.791653    0.295959    63.655818    0.371006    0.350548   
min      0.400000    0.000000     0.000000    0.000000    0.000000   
25%      2.700000    0.000000     0.000000    0.000000    0.000000   
50%      4.000000    0.000000     0.520000    0.000000    0.000000   
75%      4.900000    0.000000     6.570000    0.000000    0.000000   
max      9.400000    6.400000  1090.840000    1.000000    1.000000   

           daysat      daysun      daythu      daytue      daywed    monthapr  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     0.162476    0.183752    0.117988    0.123791    0.104449    0.017408   
std      0.369244    0.387657    0.322907    0.329662    0.306138    0.130913   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

         monthaug    monthdec    monthfeb    monthjan    monthjul    monthjun  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     0.355899    0.017408    0.038685    0.003868    0.061896    0.032882   
std      0.479249    0.130913    0.193029    0.062137    0.241199    0.178500   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      1.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

         monthmar    monthmay    monthnov    monthoct    monthsep  
count  517.000000  517.000000  517.000000  517.000000  517.000000  
mean     0.104449    0.003868    0.001934    0.029014    0.332689  
std      0.306138    0.062137    0.043980    0.168007    0.471632  
min      0.000000    0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000    0.000000    0.000000  
75%      0.000000    0.000000    0.000000    0.000000    1.000000  
max      1.000000    1.000000    1.000000    1.000000    1.000000

In [54]:
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

In [55]:
y.unique()

array(['small', 'large'], dtype=object)

## Feature Selection

In [56]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

bestfeatures=SelectKBest(score_func=chi2,k=5)
fit=bestfeatures.fit(x,y)
# calculate the scores
dfscore=pd.DataFrame(fit.scores_)
# get column names into variable
dfcolumns=pd.DataFrame(x.columns)
# concat 2 dataframe above
feat_col=pd.concat([dfcolumns,dfscore],axis=1)
feat_col.columns=['Specs','Score'] # Naming the DataFrame
print(feat_col.nlargest(7,'Score'))

#In output we can check top 5 features which we can use to make our model

       Specs         Score
8       area  15773.685520
1        DMC     23.006108
2         DC     21.872657
18  monthdec     17.601210
5         RH      6.350054
7       rain      5.216072
6       wind      1.440661


In [62]:
x.columns

Index(['FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind', 'rain', 'area',
       'dayfri', 'daymon', 'daysat', 'daysun', 'daythu', 'daytue', 'daywed',
       'monthapr', 'monthaug', 'monthdec', 'monthfeb', 'monthjan', 'monthjul',
       'monthjun', 'monthmar', 'monthmay', 'monthnov', 'monthoct', 'monthsep'],
      dtype='object')

In [64]:
X=x.loc[:,['area','DMC','DC','RH','rain','wind','monthapr', 'monthaug', 'monthdec', 'monthfeb', 'monthjan', 'monthjul','monthjun', 'monthmar', 'monthmay', 'monthnov', 'monthoct', 'monthsep']]

In [65]:
X

area    DMC     DC  RH  rain  wind  monthapr  monthaug  monthdec  \
0     0.00   26.2   94.3  51   0.0   6.7         0         0         0   
1     0.00   35.4  669.1  33   0.0   0.9         0         0         0   
2     0.00   43.7  686.9  33   0.0   1.3         0         0         0   
3     0.00   33.3   77.5  97   0.2   4.0         0         0         0   
4     0.00   51.3  102.2  99   0.0   1.8         0         0         0   
..     ...    ...    ...  ..   ...   ...       ...       ...       ...   
512   6.44   56.7  665.6  32   0.0   2.7         0         1         0   
513  54.29   56.7  665.6  71   0.0   5.8         0         1         0   
514  11.16   56.7  665.6  70   0.0   6.7         0         1         0   
515   0.00  146.0  614.7  42   0.0   4.0         0         1         0   
516   0.00    3.0  106.7  31   0.0   4.5         0         0         0   

     monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0           0         0         0         0         1         0         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         1         0         0   
4           0         0         0         0         1         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         1   

     monthoct  monthsep  
0           0         0  
1           1         0  
2           1         0  
3           0         0  
4           0         0  
..        ...       ...  
512         0         0  
513         0         0  
514         0         0  
515         0         0  
516         0         0  

[517 rows x 18 columns]

# Processing using only selected features in variable X
## Spliting data

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35, random_state = 0)

## Feature Scaling

In [67]:
X_train

area    DMC     DC   RH  rain  wind  monthapr  monthaug  monthdec  \
504  49.59  139.4  689.1   29   0.0   4.9         0         1         0   
379   0.00    1.1  171.4  100   0.0   0.9         0         0         0   
295   0.00  180.4  430.8   48   0.0   1.3         0         0         0   
219  31.86   39.7   86.6   27   0.0   3.1         0         0         0   
508   0.00  166.9  752.6   41   0.0   3.6         0         1         0   
..     ...    ...    ...  ...   ...   ...       ...       ...       ...   
70    0.00   48.3   97.8   27   0.0   7.6         0         0         0   
277  10.73   25.4  349.7   21   0.0   8.5         0         0         1   
9     0.00   88.0  698.6   40   0.0   4.0         0         0         0   
359   8.12  122.0  789.7   39   0.0   2.2         0         0         0   
192   8.71  108.3  647.1   22   0.0   4.5         0         1         0   

     monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
504         0         0         0         0         0         0         0   
379         0         1         0         0         0         0         0   
295         0         0         0         1         0         0         0   
219         0         0         0         0         1         0         0   
508         0         0         0         0         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
70          0         0         0         0         1         0         0   
277         0         0         0         0         0         0         0   
9           0         0         0         0         0         0         0   
359         0         0         0         0         0         0         0   
192         0         0         0         0         0         0         0   

     monthoct  monthsep  
504         0         0  
379         0         0  
295         0         0  
219         0         0  
508         0         0  
..        ...       ...  
70          0         0  
277         0         0  
9           0         1  
359         0         1  
192         0         0  

[336 rows x 18 columns]

In [68]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [69]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 52   1]
 [  1 127]]


0.988950276243094

## Hence we can see that only with 5 features we can acheive target of 98.89%

### poly method

In [73]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'poly', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='poly', random_state=0)

In [74]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  8  45]
 [  0 128]]


0.7513812154696132

## rbf

In [75]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [76]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  3  50]
 [  0 128]]


0.7237569060773481

## Sigmoid

In [77]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'sigmoid', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='sigmoid', random_state=0)

In [78]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  4  49]
 [  2 126]]


0.7182320441988951

#### As per above observations we can  see best results are acquired using linear function